version: 4
common:
  train_log_path: C:\Users\miger\Desktop\Simod\resources\config\..\event_logs\AcademicCredentials_train.csv.gz
  test_log_path: null
  log_ids:
    case: case_id
    activity: activity
    resource: resource
    start_time: start_time
    end_time: end_time
    enabled_time: enabled_time
    enabling_activity: enabling_activity
    available_time: available_time
    estimated_start_time: estimated_start_time
    batch_id: batch_instance_id
    batch_type: batch_instance_type
  process_model_path: C:\Users\miger\Desktop\Simod\resources\config\..\models\AcademicCredentials_SIMOD.bpmn
  num_final_evaluations: 0
  evaluation_metrics: []
  use_observed_arrival_distribution: false
  clean_intermediate_files: true
  discover_case_attributes: false
preprocessing:
  multitasking: false
  enable_time_concurrency_threshold: 0.75
  concurrency_df: 0.9
  concurrency_l2l: 0.9
  concurrency_l1l: 0.9
control_flow:
  optimization_metric: two_gram_distance
  num_iterations: 5
  num_evaluations_per_iteration: 3
  gateway_probabilities:
  - equiprobable
  - discovery
resource_model:
  optimization_metric: circadian_event_distribution
  num_iterations: 20
  num_evaluations_per_iteration: 3
  discovery_type: differentiated_by_pool
  discover_prioritization_rules: false
  discover_batching_rules: false
  granularity: !!python/tuple
  - 15
  - 60
  confidence: !!python/tuple
  - 0.5
  - 0.85
  support: !!python/tuple
  - 0.05
  - 0.5
  participation: 0.4
extraneous_activity_delays:
  optimization_metric: RELATIVE_EMD
  discovery_method: COMPLEX
  num_iterations: 1
  num_evaluations_per_iteration: 3
